# Generated by Django 4.2.1 on 2023-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answerd_by',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questions',
            field=models.TextField(),
        ),
    ]
